name: Update README
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: 'Chore: Update Activity'
          MAX_LINES: 10
          GH_USERNAME: tooniez
          TARGET_FILE: 'README.md'
          EMPTY_COMMIT_MSG: 'Chore: No activity'